### PR TITLE
NEW: add sendMessage, add playSound, re-use auth data

### PR DESCRIPTION
**Pull request by martijnpoppen**
Hey @CaramelFur 
Awesome work!

I added some function, hope you want to merge these :D 

- Added a function to play a sound on a device
- Added a function to send a message to a device
- Added a function to set the authData. So you can store it somewhere else. This saves you a login

### CODE REVIEW

**Comment by CaramelFur** [comment]
Heya, thanks for the good ideas, I'll be testing it for a little bit to see if everything works fine. 
Cause I don't know for how long the authdata you want to store is actually valid. If its only like 5 minutes, it doesn't improve things that much.
I'll let you know when I've tested it. ^^

**Comment by CaramelFur** [comment]
I added your commits, but decided to change quite some things after that to make it easier to use/maintain.
Also i removed the storage of authdata, cause it indeed expires after 5 minutes, making it pretty much useless sadly.
If you ever have any other suggestions feel free to add them or notify me.

**Comment by martijnpoppen** [comment]
@CaramelFur Thanks!

About the storage of authData, it might be useful to do. I think if you want to fetch the location data on a interval it saves you multiple logins. :)

**Comment by CaramelFur** [comment]
I still don't really see why you would need it there, if you have a program that fetches the location more than every 5 minutes, then it'd make sense to have that just be a long running program I would say. So there is no need to store the auth data.
But please do explain some more, if I'm wrong there.

**Comment by martijnpoppen** [comment]
I would have a program that would run indefinitely and calls the API like every 1 second. If there's a update in the location I would do something with that data.

So in that case it's better to re-use the cookies to prevent a login every second.

**Comment by CaramelFur** [comment]
Ah, then you don't need to export the auth data, just make sure to keep the "FindMy" class instance alive, and you'll be fine. I've modified it so it updates the cookies with newer cookies at every request you make. So if you request the data every second, you will never have login again while the program is running (as far as i have tested). Also i would recommend like 30 sec between each request or something, it isn't going to update any faster anyways.

**Comment by martijnpoppen** [comment]
🤦🏼‍♂️  I see now yes.

Thanks will try that! Also the 30 secs make sense!

**Pull request merged**
